import NavBar from "@/components/NavBar";
import LoginForm from "@/components/auth/LoginForm";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";

const login = () => {
  const { data, status } = useSession();
  const path = useRouter();

  return (
    <div>
      <Head>
        <title>Home -Login | The Daily Grind Gym</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <NavBar />
      <LoginForm />
    </div>
  );
};

export default login;
